# Generated by Django 4.2.7 on 2024-04-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="status",
            field=models.CharField(
                choices=[
                    ("Прийнято", "Accepted"),
                    ("Відхилено", "Rejected"),
                    ("В очікуванні", "Pending"),
                ],
                max_length=120,
            ),
        ),
    ]
