# Generated by Django 4.2.7 on 2024-04-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="is_accepted",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
